version: '3'
services:
  registry:
    image: ust_teastore_registry:latest
    expose:
      - "8080"
  db:
    image: ust_teastore_database:latest
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    image: ust_teastore_persistence:latest
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
  auth:
    image: ust_teastore_auth:latest
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
  image:
    image: ust_teastore_image:latest
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
  recommender:
    image: ust_teastore_recommender:latest
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
  webui:
    image: ust_teastore_webui:latest
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8080:8080"